export const site = { name: "Omasanjuwa Andrew Etsano", shortName: "Omasan Etsano", initials: "OE", role: "Software engineer", email: "etsanoomasan@gmail.com", phone: "+234 816 561 3991", location: "Abuja, Nigeria", availability: "Available for select projects", github: "https://github.com/omasanetsano", linkedin: "https://www.linkedin.com/in/omasan-etsano-317219287/", bookdex:"https://bookdex.site" };
export const bio = "Software engineer and AI evaluation contractor with hands-on experience across full-stack product development, coding-agent benchmark design, enterprise QA, technical documentation and public-health systems. I care about clear interfaces, dependable systems and the details that help software work in the real world. I am currently completing an MS in Data Science and AI while deepening my DevOps practice.";
export const experience = [
  { period:"2026 — NOW", role:"AI Coding-Agent Evaluation · Task Author", company:"Shipd · Project Olympus", summary:"Designing benchmark tasks, reference implementations, adversarial probes and offline test harnesses for autonomous coding agents working on production Rust codebases.", points:["Authored end-to-end tasks on production Rust projects (sqlx and sea-orm): a reference implementation, an 80+ case test suite, a containerised offline harness and a specification precise enough to solve from.","Built SQLite and PostgreSQL fixture capture and snapshot diffing covering 30+ column types, foreign-key-ordered replay and cyclic tables.","Calibrated difficulty empirically: 10 agents per revision, holding pass rates inside the required 10 to 50% band across many rounds.","Built a 30+ case adversarial probe suite and cleared a multi-stage review funnel, with one task approved at human review."] },
  { period:"JAN 2026 — NOW", role:"DevOps Intern", company:"Georgetown Global Health Nigeria", summary:"Supporting national public-health and enterprise systems through frontend and API work, QA/UAT, documentation, data validation, Linux workflows and application delivery.", points:["Built the frontend and REST API integrations for the Knight Data Repository, a centralized health-dataset platform with a geographic dashboard.","Wrote workflow documentation and interactive testing dashboards covering 70+ requirements across 13 modules for the NPHCDA ERP.","Converted training quizzes into Moodle Aiken and GIFT formats across five languages: English, Hausa, Igbo, Yoruba and Pidgin.","Mapped national DR-TB forms to DHIS2 and supervised field assessors and KoboToolbox validation across Edo, Bayelsa and Cross River."] },
  { period:"JAN — JUL 2024", role:"Frontend Developer Intern · Content Reviewer", company:"Flexisaf Edusoft", summary:"Built React interface components within an existing production codebase and quality-checked more than 200 AI-generated educational items.", points:["Joined an existing production codebase and built UI components with HTML, CSS, JavaScript and React in Agile workflows.","Reviewed and quality-checked AI-generated quiz content, improving accuracy across 200+ items."] },
] as const;
export const openSource = { period:"OPEN SOURCE", role:"SQL optimizer contribution", company:"sqlglot", summary:"Implemented a simplify_joins optimizer rule following the codebase's conventions, validating correctness against DuckDB." } as const;
export const education = [
  { period:"2026 — NOW", degree:"MS Data Science and AI", school:"Campbellsville University", detail:"AI ethics, AI applications, supply-chain AI and research methods." },
  { period:"2021 — 2025", degree:"BSc Software Engineering", school:"Babcock University", detail:"Software engineering foundations and applied product development." },
] as const;
export const certifications = ["IBM DevOps & Software Engineering Professional Certificate","Python for Data Science, AI & Development","Containers with Docker, Kubernetes & OpenShift"] as const;
export const skillGroups = [
  {name:"Languages",items:["TypeScript","JavaScript","Python","SQL","HTML/CSS","Rust evaluation"]},
  {name:"Product engineering",items:["React","Next.js","Vite","Tailwind CSS","TanStack Query","Framer Motion","shadcn/ui"]},
  {name:"Backend and data",items:["Node.js","Django/DRF","Supabase","PostgreSQL","SQLite","REST APIs","DHIS2","KoboToolbox"]},
  {name:"AI and evaluation",items:["Agent benchmarks","RAG pipelines","LLM integration","Adversarial testing","Statistical evaluation"]},
  {name:"DevOps and tooling",items:["Git/GitHub","Docker","Linux","Bash","PowerShell","Playwright","Vercel","CI debugging"]},
  {name:"Documentation",items:["SRS structuring","Mermaid flowcharts","Moodle Aiken/GIFT","DOCX scripting","UAT and QA"]},
] as const;
export type Project = { slug:string; title:string; type:string; year:string; tone:string; number:string; image:string; logo:string; secondaryImage?:string; phone?:string; url?:string; repository?:string; client:string; summary:string; challenge:string; solution:string; outcome:string; stack:readonly string[] };
export const projects: readonly Project[] = [
  { slug:"bookdex", title:"BookDex", type:"Solo SaaS · Full-stack development", year:"2025 — NOW", tone:"blue", number:"01", image:"/projects/bookdex-site.jpg", logo:"/brands/bookdex.svg", client:"Independent product", url:"https://bookdex.site", summary:"A multi-tenant platform for bookings, deposits, client management and invoicing, built for service businesses in Nigeria.", challenge:"Service businesses often piece together calendars, messages, payment records and client notes. The product needed to make that operational complexity feel calm while enforcing secure separation between businesses and staff roles.", solution:"I designed and shipped the product solo, building responsive booking and dashboard flows, PostgreSQL Row Level Security, staff permissions, Edge Functions, notifications and client-side PDF invoices.", outcome:"A deployed SaaS product with tenant isolation, production authentication, Nigeria-focused SEO, Core Web Vitals tracking and email and WhatsApp confirmation workflows.", stack:["React","TypeScript","Supabase","PostgreSQL","Vite","Vercel"], repository:"https://github.com/omasanetsano" },
  { slug:"zolig-consulting", title:"ZOLIG Consulting", type:"Web development · Deployment", year:"2026", tone:"green", number:"02", image:"/projects/zolig-site.jpg", logo:"/brands/zolig.png", client:"ZOLIG Consulting Limited", url:"https://zolig-constructionltd.vercel.app/", summary:"A modern corporate platform for a Nigerian company working across construction, procurement and protective equipment.", challenge:"Three distinct service lines had to read as one credible company while preserving the existing green identity and giving the team room to manage growing content.", solution:"I built the company site in Next.js 16 and React 19 around a clear Build, Supply, Protect narrative: service, project, gallery and journal pages with responsive layouts and an enquiry form. I then prepared it to run natively on Vercel, replacing the Cloudflare-specific pieces of the original export.", outcome:"A live company website on Vercel. Public pages are served from bundled content. The content manager is paused until Vercel-compatible authentication and storage are connected.", stack:["Next.js","React","TypeScript","Tailwind CSS","Vercel"], repository:"https://github.com/omasanetsano/zolig" },
  { slug:"shefguide", title:"ShefGuide", type:"AI product · Collaborative MSc project", year:"2026", tone:"sand", number:"03", image:"/projects/shefguide-site.jpg", logo:"/brands/shefguide.svg", secondaryImage:"/projects/shefguide-chat.png", client:"MSc dissertation project", url:"https://shefguide.onrender.com/", summary:"An AI academic-support platform designed to help international students understand UK university life and turn uncertainty into a useful next step.", challenge:"Academic guidance can be fragmented, formal and difficult to navigate—especially for students adapting to a new educational culture.", solution:"In this collaborative build, I created the React and TypeScript frontend, the dual-source RAG pipeline with provider switching, and the evaluation harness with statistical tests and eight prompt-injection attacks.", outcome:"A completed research product combining a calm student experience with retrieval, multi-provider LLM integration and measurable safety and quality evaluation.", stack:["React","TypeScript","Python","RAG","OpenAI","Gemini"], repository:"https://github.com/omasanetsano" },
  { slug:"bomas-academy", title:"Bomas Academy", type:"Web redesign · Development", year:"2026", tone:"coral", number:"04", image:"/projects/bomas-home.png", logo:"/brands/bomas.jpg", client:"Bomas Academy", url:"https://www.bomasacademy.org/", summary:"A confident, family-friendly digital home for a school in Jos, supporting discovery, admissions and ongoing communication with its community.", challenge:"The school needed a site that could express its character, explain every learning stage and remain practical for staff to update without developer support.", solution:"Starting from the school’s existing TanStack Start and Supabase codebase, I redesigned the public site (navigation and mobile menu, home, academics, admissions, school life, news and gallery) and the staff admin area (overview, website content, staff, news and gallery), then moved the build onto a TanStack Start version Vercel accepts.", outcome:"A live school website with clear admissions pathways, real campus photography and a Supabase-backed admin area that staff can use to update content.", stack:["React","TypeScript","TanStack Start","Supabase","Tailwind CSS","Framer Motion"], repository:"https://github.com/omasanetsano" },
] as const;
export const services = [
  { name: "Frontend Engineering", detail: "Responsive interfaces with strong systems, interaction and motion.", tags: ["React", "Next.js", "TypeScript"] },
  { name: "Full-stack Products", detail: "End-to-end web products shaped around real users and operations.", tags: ["APIs", "Databases", "Auth"] },
  { name: "Web Design", detail: "Clear visual direction, thoughtful architecture and production-ready UI.", tags: ["UX/UI", "Systems", "Prototype"] },
  { name: "DevOps Foundations", detail: "Practical deployment and delivery workflows as I deepen my DevOps practice.", tags: ["Vercel", "CI/CD", "Cloud"] },
] as const;
export const faqs = [
  ["What do you build?", "I design and build responsive websites, full-stack web products and content systems, with a particular focus on frontend quality."],
  ["Can you handle both design and development?", "Yes. I can take a product from structure and visual direction through responsive implementation, APIs and deployment."],
  ["What is your current technical focus?", "React, Next.js and TypeScript are central to my work. I am also developing deeper DevOps skills around reliable delivery and cloud infrastructure."],
  ["Are you available for new work?", "Yes. I am available for selected product, website and frontend engineering projects."],
] as const;

