import { ArrowUpRight, BadgeCheck, BriefcaseBusiness, Cpu, Download, GraduationCap } from "lucide-react";
import { SiteFooter, SiteHeader } from "../../components/portfolio-home.tsx";
import { SocialMark, TechBadge } from "../../components/brand-icons.tsx";
import { bio, certifications, education, experience, site, skillGroups } from "../../content/site.ts";

export const metadata={title:"About Omasan Etsano — Software Engineer",description:"Software engineer working across full-stack products, AI evaluation, public-health systems and DevOps."};

export default function AboutPage(){return <main><SiteHeader/><section className="about-hero frame contour"><p className="eyebrow">ABOUT / PROFILE</p><h1>Engineer by practice.<br/><em>Curious by default.</em></h1><div className="about-lead"><p>{bio}</p><div><a href={site.github} target="_blank" rel="noreferrer"><SocialMark name="github"/> GITHUB <ArrowUpRight size={15}/></a><a href={site.linkedin} target="_blank" rel="noreferrer"><SocialMark name="linkedin"/> LINKEDIN <ArrowUpRight size={15}/></a><a href="/Omasan_Etsano_CV.pdf" download>DOWNLOAD CV <Download size={15}/></a></div></div></section><section className="profile-section frame"><header><BriefcaseBusiness className="profile-icon"/><p className="eyebrow">01 / EXPERIENCE</p><h2>Work that crosses<br/>disciplines and systems.</h2></header><div className="profile-list">{experience.map(item=><article key={item.role}><span>{item.period}</span><div><p>{item.company}</p><h3>{item.role}</h3><p>{item.summary}</p></div></article>)}</div></section><section className="profile-section profile-light frame"><header><GraduationCap className="profile-icon"/><p className="eyebrow">02 / EDUCATION</p><h2>Learning in progress.</h2></header><div className="profile-list">{education.map(item=><article key={item.degree}><span>{item.period}</span><div><p>{item.school}</p><h3>{item.degree}</h3><p>{item.detail}</p></div></article>)}</div></section><section className="profile-section frame"><header><Cpu className="profile-icon"/><p className="eyebrow">03 / TECHNICAL RANGE</p><h2>From interface to<br/>infrastructure.</h2></header><div className="skill-matrix">{skillGroups.map(group=><article key={group.name}><h3>{group.name}</h3><div>{group.items.map(item=><TechBadge name={item} key={item}/>)}</div></article>)}</div></section><section className="profile-section certifications frame"><header><BadgeCheck className="profile-icon"/><p className="eyebrow">04 / CERTIFICATIONS</p><h2>Formal foundations.</h2></header><ol>{certifications.map((item,i)=><li key={item}><BadgeCheck size={17}/><span>0{i+1}</span>{item}</li>)}</ol></section><SiteFooter/></main>}


