import { notFound } from "next/navigation";
import Link from "next/link";
import Image from "next/image";
import { ArrowLeft, ArrowUpRight, ExternalLink } from "lucide-react";
import { ProjectVisual, SiteFooter, SiteHeader } from "../../../components/portfolio-home.tsx";
import { projects } from "../../../content/site.ts";
import { TechBadge } from "../../../components/brand-icons.tsx";

export function generateStaticParams(){return projects.map(p=>({slug:p.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=projects.find(x=>x.slug===slug);return p?{title:`${p.title} — Omasan Etsano`,description:p.summary}:{}}
export default async function WorkDetail({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=projects.find(x=>x.slug===slug);if(!p)notFound();const next=projects[(projects.indexOf(p)+1)%projects.length];return <main><SiteHeader/><section className="case-head frame"><Link href="/works" className="back-link"><ArrowLeft size={15}/> ALL WORK</Link><p className="eyebrow">SELECTED WORK / {p.number}</p><h1>{p.title}</h1><div className="case-intro"><p>{p.summary}</p>{p.url&&<a href={p.url} target="_blank" rel="noreferrer">VIEW LIVE SITE <ExternalLink size={16}/></a>}</div></section><section className="case-meta frame">{[["YEAR",p.year],["DISCIPLINE",p.type],["CLIENT",p.client],["STATUS",p.url?"LIVE":"PRODUCT BUILD"]].map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</section><section className="case-art frame"><ProjectVisual project={p}/></section><section className="case-copy frame"><p className="eyebrow">THE PROJECT</p><h2>{p.challenge}</h2><div><p>{p.solution}</p><p>{p.outcome}</p></div></section><section className="project-stack frame"><p className="eyebrow">BUILD STACK</p><div>{p.stack.map(item=><TechBadge name={item} key={item}/>)}</div>{p.repository&&<a href={p.repository} target="_blank" rel="noreferrer">VIEW GITHUB <ArrowUpRight size={16}/></a>}</section>{p.secondaryImage&&<section className="case-secondary frame"><Image src={p.secondaryImage} alt={`${p.title} interface detail`} width={1440} height={900}/></section>}<section className="next-case frame"><Link href={`/works/${next.slug}`}><span>NEXT PROJECT / {next.number}</span><b>{next.title}</b><ArrowUpRight/></Link></section><SiteFooter/></main>}
